parameters:
#    polcode_shop.example.class: Polcode\ShopBundle\Example

services:
#    polcode_shop.example:
#        class: %polcode_shop.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
